// livros-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
 selector: 'app-livro-dados',
 templateUrl: './livro-dados.component.html',
 styleUrls: ['./livro-dados.component.css'],
 standalone: true,
 imports: [FormsModule, CommonModule],
})
export class LivroDadosComponent implements OnInit {
 public livro: Livro = new Livro('', 1, '', '', []);
 public editoras: Array<Editora> = [];

 constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
 ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras()
  }

  incluir(): void {
    this.servLivros.incluir(this.livro).then(() => {
       this.router.navigateByUrl('/lista');
    });
  }
}

<main class="container my-4">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
     <div class="form-group">
       <label for="titulo">Título</label>
       <input type="text" class="form-control" id="titulo" name="titulo" [(ngModel)]="livro.titulo" required>
     </div>
     <div class="form-group">
       <label for="resumo">Resumo</label>
       <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo"></textarea>
     </div>
     <div class="form-group">
       <label for="editora">Editora</label>
       <select class="form-control" id="editora" name="editora" [(ngModel)]="livro.codEditora" required>
         <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{editora.nome}}</option>
       </select>
     </div>
     <div class="form-group">
       <label for="autores">Autores (1 por linha)</label>
       <textarea class="form-control" id="autores" name="autores" [(ngModel)]="livro.autores"></textarea>
     </div>
     <button type="submit" class="btn btn-primary">Salvar dados</button>
  </form>
</main>

// livros-servidor/clientes/livros-react/src/livrodados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { ControleLivro } from './controle/ControleLivros';
const controlador = new ControleLivro

export const obterLivros = () => {
  const livrosSalvos = localStorage.getItem('livros');
  return livrosSalvos ? JSON.parse(livrosSalvos) : [];
};

const LivroDados = () => {
  const navigate = useNavigate();
  
  const opcoes = [
    { codEditora: 1, nome: "Alta Books" },
    { codEditora: 2, nome: "Bookman" },
    { codEditora: 3, nome: "Addison Wesley" },
    { codEditora: 4, nome: "Pearson" },
  ];

  // Inicializa codEditora com o valor do primeiro item de opcoes como string
  const [codEditora, setCodEditora] = useState(opcoes[0]?.codEditora.toString());
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');

  const tratarCombo = (evento) => {
    setCodEditora(evento.target.value);
  };

  const incluir = (evento) => {
    evento.preventDefault();

    const novoLivro = {
      titulo,
      resumo,
      codEditora: Number(codEditora) ?? 1,
      autores
    };

    controlador.adicionarLivro(novoLivro).then(() => {
      navigate('/');
    });
  };

  return (
    <div className="container mt-5">
      <h2>Cadastro de Livro</h2>
      <form onSubmit={incluir}>
        <div className="mb-3">
          <label htmlFor="titulo">Título</label>
          <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
        </div>
        <div className="mb-3">
          <label htmlFor="resumo">Resumo</label>
          <textarea className="form-control" id="resumo" value={resumo} onChange={(e) => setResumo(e.target.value)}></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="editora">Editora</label>
          <select className="form-select" id="editora" value={codEditora} onChange={tratarCombo}>
            {opcoes.map(opcao => (
              <option key={opcao.codEditora} value={opcao.codEditora}>{opcao.nome}</option>
            ))}
          </select>
        </div>
        <div className="mb-3">
          <label htmlFor="autores">Autores (1 por linha)</label>
          <textarea className="form-control" id="autores" value={autores} onChange={(e) => setAutores(e.target.value)}></textarea>
        </div>
        <button type="submit" className="btn btn-primary">Salvar Dados</button>
      </form>
    </div>
  );
};

export default LivroDados;
