// livros-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { CommonModule } from '@angular/common';

@Component({
 selector: 'app-livro-lista',
 templateUrl: './livro-lista.component.html',
 styleUrls: ['./livro-lista.component.css'],
 standalone: true,
 imports: [CommonModule],
})
export class LivroListaComponent implements OnInit {
 public editoras: Editora[] = [];
 public livros: Livro[] = [];

 constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

 ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros:Livro[]) => {
      this.livros = livros;
    });
 }

 excluir(codigo: string | null | undefined): void {
  this.servLivros.excluir(codigo).then(() => {
    this.servLivros.obterLivros().then((livros:Livro[]) => {
      this.livros = livros;
    });
  });
 }

 obterNome = (codEditora: number | null | undefined): string => {
    return this.servEditora.getNomeEditora(codEditora);
 }
}

<main class="container">
  <h1 class="my-4">Catálogo de Livros</h1>
  <table class="table table-striped">
     <thead class="navbar-dark bg-dark text-white">
       <tr>
         <th>Título</th>
         <th>Resumo</th>
         <th>Editora</th>
         <th>Autores</th>
       </tr>
     </thead>
     <tbody>
       <tr *ngFor="let livro of livros">
         <td>
          <div>
            {{ livro.titulo }}
          </div>
          <button class="btn btn-danger" (click)="excluir(livro._id)">Excluir</button>
          </td>
          <td>
           {{ livro.resumo }}
          </td>
         <td>{{ obterNome(livro.codEditora) }}</td>
         <td>
           <ul>
             <li *ngFor="let autor of livro.autores">{{ autor }}</li>
           </ul>
         </td>

       </tr>
     </tbody>
  </table>
</main>

// livros-servidor/clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import { ControleLivro } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const controlador = new ControleLivro
const editoraControlador = new ControleEditora

const LivroLista = () => {
  const [livros, setLivros] = useState([]);

  useEffect(() => {
    controlador.obterLivros().then(livros => {
      setLivros(livros);
    });
  }, []);

  const excluirLivro = (codigo) => {
    controlador.removerLivro(codigo).then(() => {
      controlador.obterLivros().then(livros => {
        setLivros(livros);
      });
    }).catch((error)=> {
      console.log(error, 'excluirLivro')
    });
  };

  return (
    <div className="container mt-5">
      <table className="table table-striped">
        <thead className="table-dark">
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <tr key={index}>
              <td>
                {livro.titulo}
                <br />
                <button 
                  className="btn btn-danger btn-sm mt-2" 
                  onClick={() => excluirLivro(livro._id)}
                >
                  Excluir
                </button>
              </td>
              <td>{livro.resumo}</td>
              <td>{ editoraControlador.getEditoraPorCodigo(livro.codEditora)?.nome ?? '-'}</td>
              <td dangerouslySetInnerHTML={{ __html: livro.autores.join(' <br> ') }}></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default LivroLista;
